# rotate:
#   clockwise:
#     command: "hyprctl resizeactive, 15 0"
#   counterclockwise:
#     command: "hyprctl resizeactive, -15 0"
swipe:
  3:
    up:
      command: "hyprctl dispatch fullscreen 1" # Activity
    down:
      command: "hyprctl dispatch fullscreen 0" # Activity
pinch:
  2:
    in:
      command: "xdotool keydown ctrl click 4 keyup ctrl" # threshold: 0.5, interval: 0.5
    out:
      command: "xdotool keydown ctrl click 5 keyup ctrl" # threshold: 0.5, interval: 0.5

threshold:
  pinch: 0.5

interval:
  swipe: 0.75
  pinch: 0.5
