{ pkgs, ... }:
{
  # Not defaultPackages: assigning that drops perl/rsync/strace.
  environment.systemPackages = [
    pkgs.impala # iwd TUI
    pkgs.iwgtk # iwd GUI
  ];

  # connman rfkill-blocks every technology saved as disabled, at each boot;
  # `rfkill unblock` doesn't persist, `connmanctl disable/enable <tech>` does.
  services.connman.enable = true;
  services.connman.wifi.backend = "iwd";
  networking.wireless.iwd.enable = true;

  # No DNS proxy: connman's caching resolver drops replies ("Bad file
  # descriptor") and is a redundant hop under tailscale. connman then writes
  # the router's nameservers, which tailscale reads as its upstream.
  services.connman.extraFlags = [ "--nodnsproxy" ];

  # Don't "fix" connmand's "Cannot create /var/run/connman/resolv.conf" boot
  # message with a RuntimeDirectory: its fallback write to /etc/resolv.conf is
  # how tailscaled (direct mode) learns the upstream resolver.

  # Keeps openresolv off tailscaled's PATH so it uses direct mode: openresolv
  # rejects the resolv.conf connman writes (no "Generated by resolvconf"
  # signature), which broke every DNS push.
  networking.resolvconf.enable = false;

  # No online check. It probes ipv4.connman.net and ipv6.connman.net, and one
  # of the two has timed out every day since this machine went live (v4 until
  # 2026-10-01, v6 since), so connman retried forever: a 2-minute TCP timeout
  # and a journal warning every ~4.5 min. Services now rest at "ready", not
  # "online"; nothing here reads the difference (noctalia asks iwd, and there
  # is no wait-online unit).
  services.connman.extraConfig = ''
    OnlineCheckMode=none
  '';

  # Reached over the tailnet only: tailscale0 is a trusted interface
  # (./tailscale.nix), so the firewall stays shut to every other network. The
  # module opens port 22 on all interfaces by default, and sshd still takes
  # passwords.
  services.openssh = {
    enable = true;
    openFirewall = false;
  };

  # mDNS / `.local` resolution.
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };

  # No networking.useDHCP: connman does DHCP itself, and its module asserts
  # useDHCP is false.
}
