{ options, ... }:
{
  # Enrolment is a one-off `sudo tailscale up`; state is in /var/lib/tailscale.
  services.tailscale = {
    enable = true;
    # Loose reverse-path filtering, so replies through an exit node get in.
    # Serving as an exit node or subnet router would need "both".
    useRoutingFeatures = "client";
    # 41641/udp, so peers connect directly instead of through DERP relays.
    openFirewall = true;
  };

  # After a hard power-off tailscaled's own /etc/resolv.conf is still in place,
  # and its header (".../s/resolvconf-overwrite") makes the next tailscaled
  # take the file for resolvconf's. It then picks openresolv mode, finds only
  # systemd's resolvconf shim, fails every DNS push ("exit status 1") and
  # MagicDNS is gone until a restart (the boot after 2026-10-07's battery
  # death). Put the backup back first, as its own cleanup does in direct mode
  # (./network.nix has the rest of the DNS chain).
  systemd.services.tailscaled.preStart = ''
    if grep -qs 'generated by tailscale' /etc/resolv.conf; then
      mv -f /etc/resolv.pre-tailscale-backup.conf /etc/resolv.conf 2>/dev/null \
        || rm -f /etc/resolv.conf
    fi
  '';

  # Tunnel traffic skips the firewall (sshd, Taildrop, ...); access is still
  # gated by the tailnet's device list and ACLs.
  networking.firewall.trustedInterfaces = [ "tailscale0" ];

  # Stops connman running DHCP on tailscale0 (entries are prefixes). Appended
  # to the option's default, which a plain definition would replace.
  services.connman.networkInterfaceBlacklist =
    options.services.connman.networkInterfaceBlacklist.default
    ++ [ "tailscale" ];
}
