ENV_VARS:
  PS4_ADDR: 10.42.0.250 # In Playstation, go to Settings -> Network -> Network status. THIS CHANGES OFTEN
  TF_USE_LEGACY_KERAS: 1 # TODO: change this to be added elsewhere
  ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE: "fg=8" # to have completion suggestions look gray
  # I don't like this, since some home-manager update I have to do this, otherwise the user "daniel" is not modified
  STARSHIP_CONFIG: "/home/dev/.config/starship.toml"
  XDG_STATE_HOME: "/home/dev/.local/state"
  XDG_DATA_HOME: "/home/dev/.local/share"
  GTK2_RC_FILES: "/home/dev/.gtkrc-2.0"
  XDG_CONFIG_HOME: "/home/dev/.config"
  XDG_CACHE_HOME: "/home/dev/.cache"
  NIX_XDG_DESKTOP_PORTAL_DIR: "/etc/profiles/per-user/daniel/share/xdg-desktop-portal/portals"
  XCURSOR_PATH: "/etc/profiles/per-user/daniel/share/icons"
ADDITIONAL_MOUNTS:
  # Nix things
  - "/nix/store/:/nix/store:ro"
  - "/etc/profiles/per-user/daniel/bin/:/home/dev/.nix-profile/bin/:ro"
  - "/home/daniel/nix_config:/home/dev/nix_config"
  # Obsidian
  - "/home/daniel/vaults:/home/dev/vaults"
  # Starship: is this needed?
  - "/etc/profiles/per-user/daniel/bin/starship:/etc/profiles/per-user/daniel/bin/starship"
  - "/home/daniel/.config/starship.toml:/home/dev/.config/starship.toml"
  # zsh
  - "/home/daniel/.zsh_history:/home/dev/.zsh_history"
  - "/home/daniel/.zshenv:/home/dev/.zshenv"
  - "/home/daniel/.config/zsh:/home/dev/.config/zsh/"

  # WE DO NOT WANT THIS FILE, because this sets env variables to point to user "daniel" (host), and that's bad
  # - "/etc/profiles/per-user/daniel/etc/profile.d/hm-session-vars.sh:/etc/profiles/per-user/daniel/etc/profile.d/hm-session-vars.sh"

  # Television
  - "/home/daniel/.config/television:/home/dev/.config/television"
  # Silk
  # - "/home/daniel/Projects/silk/inso_builds/:/inso_builds/"
  # - "/home/daniel/Projects/silk/proton_7.0.4:/proton7_build"

  # Mirror Pond
  # - "/home/daniel/Projects/MirrorPond:/home/dev/MirrorPond"

  # Sparkle
  - "/home/daniel/Projects/sparkle:/home/dev/sparkle"

  # Nvim
  - "/home/daniel/.local/share/nvim/:/home/daniel/.local/share/nvim/"
  # Firefox profiles DOES NOT WORK
  - "/home/daniel/.mozilla/firefox/:/home/dev/.mozilla/firefox/"
  # IPython: DOES NOT WORK
  - "/home/daniel/nix_config/sony_ai/1_fzf_history.py:/home/dev/.ipython/profile_default/startup/1_fzf_history.py"
