# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cmp-dap = {
    pname = "cmp-dap";
    version = "d16f14a210cd28988b97ca8339d504533b7e09a4";
    src = fetchFromGitHub ({
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "d16f14a210cd28988b97ca8339d504533b7e09a4";
      fetchSubmodules = false;
      sha256 = "sha256-w+gGaZxXjb2B0dMXhfduEQKtO5CmQnuUdh4otpcsFuc=";
    });
    date = "2022-11-13";
  };
  cmp-nixpkgs = {
    pname = "cmp-nixpkgs";
    version = "940a29ccd70a20d22e357328514e2702fa8dc184";
    src = fetchFromGitHub ({
      owner = "gravndal";
      repo = "cmp-nixpkgs";
      rev = "940a29ccd70a20d22e357328514e2702fa8dc184";
      fetchSubmodules = false;
      sha256 = "sha256-jHJbriyFvh7NqviMH5rfCN4TkpACViskp7JB4z6e+X4=";
    });
    date = "2023-03-26";
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    });
    date = "2022-10-03";
  };
  fm-nvim = {
    pname = "fm-nvim";
    version = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
    src = fetchFromGitHub ({
      owner = "is0n";
      repo = "fm-nvim";
      rev = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
      fetchSubmodules = false;
      sha256 = "sha256-I29p08P4Wh/LLTDZIQ2TkYy5Kdj0G8loU6k3eFM+iVE=";
    });
    date = "2022-10-10";
  };
  lsp-lense = {
    pname = "lsp-lense";
    version = "c324b9224284219deb9988412eed1da5e2027fed";
    src = fetchFromGitHub ({
      owner = "VidocqH";
      repo = "lsp-lens.nvim";
      rev = "c324b9224284219deb9988412eed1da5e2027fed";
      fetchSubmodules = false;
      sha256 = "sha256-dU00GYYomFuxQBpNI8vqHO52BdXl6Ll0wcmiySQrhGE=";
    });
    date = "2023-04-11";
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
    date = "2021-04-20";
  };
  neodev-nvim = {
    pname = "neodev-nvim";
    version = "864b35006d3de24c60e44b566de8018f919b13e6";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "neodev.nvim";
      rev = "864b35006d3de24c60e44b566de8018f919b13e6";
      fetchSubmodules = false;
      sha256 = "sha256-d7M2ZhWsu541FgviJ7UW2Ypl16O1qR5zkjV5flfDugc=";
    });
    date = "2023-04-05";
  };
  neozoom-nvim = {
    pname = "neozoom-nvim";
    version = "33a45965f99b24a8e7da98f9c976285f946689fe";
    src = fetchFromGitHub ({
      owner = "nyngwang";
      repo = "NeoZoom.lua";
      rev = "33a45965f99b24a8e7da98f9c976285f946689fe";
      fetchSubmodules = false;
      sha256 = "sha256-ID34g+jftl41qHY6LyIFsTSsUeKF6bsRmS+2tYPsL2I=";
    });
    date = "2023-04-01";
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "d2433fba40bb023f4b05ff2f51590f415be1eb71";
    src = fetchFromGitHub ({
      owner = "epwalsh";
      repo = "obsidian.nvim";
      rev = "d2433fba40bb023f4b05ff2f51590f415be1eb71";
      fetchSubmodules = false;
      sha256 = "sha256-tkOksS2jAz9VjfBq/PtanxuWtKFEQxLbEFuLXUP5cKQ=";
    });
    date = "2023-04-04";
  };
}
