# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  cmp-dap = {
    pname = "cmp-dap";
    version = "d16f14a210cd28988b97ca8339d504533b7e09a4";
    src = fetchFromGitHub ({
      owner = "rcarriga";
      repo = "cmp-dap";
      rev = "d16f14a210cd28988b97ca8339d504533b7e09a4";
      fetchSubmodules = false;
      sha256 = "sha256-w+gGaZxXjb2B0dMXhfduEQKtO5CmQnuUdh4otpcsFuc=";
    });
  };
  cmp-nixpkgs = {
    pname = "cmp-nixpkgs";
    version = "12bebfe528ecabf65ddab5d50521487cc413ebca";
    src = fetchFromGitHub ({
      owner = "gravndal";
      repo = "cmp-nixpkgs";
      rev = "12bebfe528ecabf65ddab5d50521487cc413ebca";
      fetchSubmodules = false;
      sha256 = "sha256-kRdXFhcrAzWFK3CVt5BoQKO2HkGH2ujmtNOFX6uo9jQ=";
    });
  };
  cmp-path = {
    pname = "cmp-path";
    version = "91ff86cd9c29299a64f968ebb45846c485725f23";
    src = fetchFromGitHub ({
      owner = "hrsh7th";
      repo = "cmp-path";
      rev = "91ff86cd9c29299a64f968ebb45846c485725f23";
      fetchSubmodules = false;
      sha256 = "sha256-thppiiV3wjIaZnAXmsh7j3DUc6ceSCvGzviwFUnoPaI=";
    });
  };
  fm-nvim = {
    pname = "fm-nvim";
    version = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
    src = fetchFromGitHub ({
      owner = "is0n";
      repo = "fm-nvim";
      rev = "8e6a77049330e7c797eb9e63affd75eb796fe75e";
      fetchSubmodules = false;
      sha256 = "sha256-I29p08P4Wh/LLTDZIQ2TkYy5Kdj0G8loU6k3eFM+iVE=";
    });
  };
  manix = {
    pname = "manix";
    version = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
    src = fetchFromGitHub ({
      owner = "mlvzk";
      repo = "manix";
      rev = "d08e7ca185445b929f097f8bfb1243a8ef3e10e4";
      fetchSubmodules = false;
      sha256 = "sha256-GqPuYscLhkR5E2HnSFV4R48hCWvtM3C++3zlJhiK/aw=";
    });
  };
  neodev-nvim = {
    pname = "neodev-nvim";
    version = "f8b17d3b74aa3ead1e532d33f987b3f5f6e95138";
    src = fetchFromGitHub ({
      owner = "folke";
      repo = "neodev.nvim";
      rev = "f8b17d3b74aa3ead1e532d33f987b3f5f6e95138";
      fetchSubmodules = false;
      sha256 = "sha256-xSj8di4LmhU4KR/G0vblEOOigZc0m9sqdYRofcuUte0=";
    });
  };
  neozoom-nvim = {
    pname = "neozoom-nvim";
    version = "8ab6a565c6fc2265b7dcf9c40318887958014ac4";
    src = fetchFromGitHub ({
      owner = "nyngwang";
      repo = "NeoZoom.lua";
      rev = "8ab6a565c6fc2265b7dcf9c40318887958014ac4";
      fetchSubmodules = false;
      sha256 = "sha256-dK25ER1tcsANlrH7YIxvpivoEPgaHhNcpi5dNWTK86I=";
    });
  };
  obsidian-nvim = {
    pname = "obsidian-nvim";
    version = "5436cb037862192e24ccac89bf5fba875a54284f";
    src = fetchFromGitHub ({
      owner = "epwalsh";
      repo = "obsidian.nvim";
      rev = "5436cb037862192e24ccac89bf5fba875a54284f";
      fetchSubmodules = false;
      sha256 = "sha256-AZ0RAkpvS1s+1xzwEiLCCKNy6LtmRbKYFvt1e+avHSU=";
    });
  };
}
