# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # For theming
  programs.dconf.enable = true;

  boot = {
    loader.systemd-boot.configurationLimit = 10; # Empirically tested so that we don't run out of space in '/boot'
    initrd.availableKernelModules = [
      "nvme"
      "xhci_pci"
      "usbhid"
      "usb_storage"
      "sd_mod"
      "rtsx_pci_sdmmc"
    ];
    initrd.kernelModules = [
      "dm-snapshot"
      "amdgpu"
    ];
    kernelPackages = pkgs.linuxPackages_xanmod_latest; # Use latest kernel packages
    kernelModules = [ "kvm-amd" ];
    # This line is needed to fix suspend/wakeup issues in Hyprland
    # https://wiki.hyprland.org/Nvidia/#fixing-suspendwakeup-issues
    kernelParams = [
      "nvidia.NVreg_PreserveVideoMemoryAllocations=1" # To prevent nvidia from crashing on suspend. DOES NOT WORK when other monitors are connected
      "nvidia.NVreg_EnableS0ixPowerManagement=0" # From https://github.com/NVIDIA/open-gpu-kernel-modules/issues/472
      "nvidia-drm.modeset=1" # Needed for `gamescope`
    ];
  };

  services = {
    xserver.videoDrivers = [
      "nvidia"
      "amdgpu"
    ]; # Have nvidia and amd GPUs active
    logind.lidSwitchDocked = "suspend"; # Suspend when laptop lid is closed but computer is docked to monitors / keyboard
    logind.lidSwitch = "suspend"; # Specifies what to do when the laptop lid is closed.
  };

  hardware = {
    enableAllFirmware = true; # Enable firmware that is not free
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        libva-vdpau-driver
        # vaapiVdpau  old version, stuck cuz of manager rev=2d55a52963d8a3856792e2fd6604f307176026bc
        libvdpau-va-gl
        intel-compute-runtime
      ];
      enable32Bit = true;
    };
    nvidia = {
      # package = config.boot.kernelPackages.nvidiaPackages.stable;
      # Check values in ~/playground/nix/nixpkgs/pkgs/os-specific/linux/nvidia-x11/default.nix
      # package = config.boot.kernelPackages.nvidiaPackages.mkDriver {
      #   version = "580.95.05";
      #   sha256_64bit = "sha256-hJ7w746EK5gGss3p8RwTA9VPGpp2lGfk5dlhsv4Rgqc=";
      #   sha256_aarch64 = "sha256-zLRCbpiik2fGDa+d80wqV3ZV1U1b4lRjzNQJsLLlICk=";
      #   openSha256 = "sha256-RFwDGQOi9jVngVONCOB5m/IYKZIeGEle7h0+0yGnBEI=";
      #   settingsSha256 = "sha256-F2wmUEaRrpR1Vz0TQSwVK4Fv13f3J9NJLtBe4UP2f14=";
      #   persistencedSha256 = "sha256-QCwxXQfG/Pa7jSTBB0xD3lsIofcerAWWAHKvWjWGQtg=";
      # };
      modesetting.enable = true;
      powerManagement = {
        enable = true;
        finegrained = true;
      };
      open = false; # Don't use open source drivers (use closed-source)
      nvidiaSettings = true;
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        # Make sure to use the correct Bus ID values for your system!
        # This can be retrieved by running: sudo lshw -c display
        amdgpuBusId = "PCI:06:00:0";
        nvidiaBusId = "PCI:01:00:0";
      };
    };

    # Bluetooth
    bluetooth = {
      enable = true;
    };
  };

  # Cache for CUDA things
  nix.settings = {
    substituters = [
      "https://cuda-maintainers.cachix.org"
    ];
    trusted-public-keys = [
      "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
    ];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/9198a171-af25-4994-adc0-29dfebf18890";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/D0C6-BF0B";
    fsType = "vfat";
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/a7497916-c6b3-4da5-b587-ff8b0ce3ce20"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
