# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../bluetooth.nix
  ];

  # For theming
  programs.dconf.enable = true;

  boot = {
    kernelModules = [ "kvm-intel" ];
    # spd5118 (DDR5 RAM temperature sensor) fails to resume from suspend on this
    # machine (-ENXIO: the chip stops responding on the SMBus after S3), flooding
    # the console with "failed to resume async: error -6" and sometimes wedging
    # resume entirely. It's a diagnostics-only hwmon driver; blacklisting it only
    # costs the RAM temperature reading in `sensors`.
    blacklistedKernelModules = [ "spd5118" ];
    # The internal panel is driven by the Intel iGPU (card1-eDP-1 / i915), but on this
    # hardware the kernel registered the EC/WMI device `nvidia_wmi_ec_backlight` as the
    # backlight instead of `intel_backlight`. brightnessctl then writes to that EC device,
    # which doesn't drive the panel's PWM, so brightness never visibly changes. Forcing
    # native backlight makes i915 register `intel_backlight` (the device that works).
    kernelParams = [ "acpi_backlight=native" ];
    initrd = {
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      luks.devices."luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74".device =
        "/dev/disk/by-uuid/cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    };
    loader = {
      # systemd-boot = {
      #   configurationLimit = 10; # Empirically tested so that we don't run out of space in '/boot'
      #   enable = true;  # NOTE: hopefully this doesn't fuck things up
      # };
      efi = {
        canTouchEfiVariables = true;
        efiSysMountPoint = "/boot";
      };
      grub = {
        enable = true;
        device = "nodev";
        efiSupport = true;
        useOSProber = false;
        configurationLimit = 10;

        # Undertale mirror-scene theme: the boot menu renders inside the
        # "Despite everything, it's still you." dialogue box.
        theme = pkgs.callPackage ../grub_theme { };
        # Panel-native 16:10 mode; the theme background is authored at 1920x1200.
        gfxmodeEfi = "1920x1200,auto";

        extraEntries = ''
          # Chainload to Ubuntu's GRUB config file
          menuentry "Ubuntu" {
            insmod part_gpt
            insmod fat
            insmod search_fs_uuid
            search --set=root --fs-uuid 701C-C166
            chainloader /EFI/ubuntu/grubx64.efi.backup
          }

        '';
      };
    };
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };
  fileSystems."/home" = {
    device = "/dev/mapper/luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/701C-C166";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  services = {
    xserver.videoDrivers = [
      "nvidia"
      # "intelgpu"  # No longer working!
    ]; # Have nvidia and intel GPUs active
    logind.settings.Login.HandleLidSwitchDocked = "suspend"; # Suspend when laptop lid is closed but computer is docked to monitors / keyboard
    logind.settings.Login.HandleLidSwitch = "suspend"; # Specifies what to do when the laptop lid is closed.
  };

  hardware = {
    enableAllFirmware = true; # Enable firmware that is not free
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        libva-vdpau-driver
        libvdpau-va-gl
        intel-compute-runtime
        # intel-media-driver # iHD VA-API driver: video decode on the iGPU instead of the dGPU
      ];
      enable32Bit = true;
    };
    nvidia = {
      package = config.boot.kernelPackages.nvidiaPackages.stable;
      # package = config.boot.kernelPackages.nvidiaPackages.legacy_580;
      modesetting.enable = true;
      powerManagement = {
        enable = true;
        finegrained = true;
      };
      open = true; # Use the open-source NVIDIA kernel modules (required on newer GPUs)
      nvidiaSettings = true;
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        # Make sure to use the correct Bus ID values for your system!
        # This can be retrieved by running: sudo pciutils -c lspci -d ::03xx
        # Follow instructions in https://wiki.nixos.org/wiki/NVIDIA
        intelBusId = lib.mkForce "PCI:00:02:0";
        nvidiaBusId = lib.mkForce "PCI:02:00:0";
      };
    };

    # Bluetooth
  };

  # Cache for CUDA things
  nix.settings = {
    substituters = [
      "https://cuda-maintainers.cachix.org"
    ];
    trusted-public-keys = [
      "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
