# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../bluetooth.nix
  ];

  # Hide sinks that are never the intended output: the nvidia GB203's HDMI
  # "pro-output" ports (no display audio is ever plugged into the dGPU) and
  # the ACE controller's HDMI1-3 ports (unplugged monitor-audio outputs).
  # Keeps the ACE "Speaker" (internal speakers) and any Bluetooth sink
  # selectable in pavucontrol.
  services.pipewire.wireplumber.extraConfig."51-hide-unwanted-sinks" = {
    "monitor.alsa.rules" = [
      {
        matches = [
          { "node.name" = "~alsa_output.pci-0000_02_00.1.pro-output-.*"; }
          {
            "node.name" = "~alsa_output.pci-0000_80_1f.3-platform-skl_hda_dsp_generic.HiFi__HDMI[0-9]__sink";
          }
        ];
        actions = {
          update-props = {
            "node.disabled" = true;
          };
        };
      }
    ];
  };

  boot = {
    kernelPackages = pkgs.linuxPackages_latest;
    kernelModules = [ "kvm-intel" ];
    # spd5118 (DDR5 RAM temperature sensor) fails to resume from suspend on this
    # machine (-ENXIO: the chip stops responding on the SMBus after S3), flooding
    # the console with "failed to resume async: error -6" and sometimes wedging
    # resume entirely. It's a diagnostics-only hwmon driver; blacklisting it only
    # costs the RAM temperature reading in `sensors`.
    blacklistedKernelModules = [ "spd5118" ];
    # The internal panel is driven by the Intel iGPU (card1-eDP-1 / xe), but on this
    # hardware the kernel registered the EC/WMI device `nvidia_wmi_ec_backlight` as the
    # backlight instead of `intel_backlight`. Forcing native backlight makes the iGPU
    # register `intel_backlight` (the device that actually drives the panel's PWM).
    #
    # This param does its job, but it is only half the fix: the nvidia driver still
    # registers a phantom `nvidia_0` backlight under 0000:02:00.0 for its own
    # card0-eDP-2 connector -- which is *disconnected*, since the panel hangs off the
    # iGPU. Bare `brightnessctl` enumerates nvidia_0 first and writes there, where the
    # writes silently succeed and change nothing. Every consumer must therefore name
    # the device explicitly (see `-d intel_backlight` in hyprland/hyprland.lua and
    # noctalia's monitor."eDP-1".backend in noctalia/default.nix).
    kernelParams = [
      "acpi_backlight=native"
      # Serial console printk is synchronous and surprisingly slow during
      # boot; errors still print (loglevel unaffected for warnings+).
      "quiet"
      # Deliberate security tradeoff (accepted 2026-08-06): disables Spectre-
      # class speculative-execution mitigations for measurable syscall/IO
      # speedup. Remove this line to restore full mitigation.
      "mitigations=off"
    ];
    initrd = {
      # systemd initrd: parallel device probing, the LUKS prompt comes up
      # sooner (systemd-ask-password), and initrd time finally decomposes in
      # `systemd-analyze blame --initrd` instead of one opaque number.
      systemd.enable = true;
      verbose = false;
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      luks.devices."luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74" = {
        device = "/dev/disk/by-uuid/cf747f68-c4d1-4a72-8589-e8ca20b09a74";
        # Pass TRIM through dm-crypt so discard=async (and the weekly
        # fstrim.timer) actually reach the SSD; without this the drive's FTL
        # has never learned which blocks are free. Tradeoff: an attacker with
        # the raw disk can see which blocks are unused.
        allowDiscards = true;
      };
    };
    loader = {
      # GRUB, not systemd-boot: the Undertale theme below is the point.
      #
      # 2026-09-09..12 boot incident (`grub rescue>` "symbol 'grub_memcpy' not
      # found", then a systemd-boot entry for a closure deleted months ago).
      # The cause was not GRUB or a stale ESP: rebuilds had been landing on
      # the ESP all along. It was three loaders on one ESP, picked by an
      # INSYDE firmware whose BootOrder never kept the "NixOS-boot" NVRAM
      # entry efibootmgr created: first the "ubuntu" entry, whose
      # \EFI\ubuntu\shimx64.efi was not Ubuntu's shim (that sits beside it as
      # shimx64.efi.backup) but an older GRUB core copied there in 2025-12 so
      # this firmware would boot NixOS at all (it reads modules from OUR
      # /boot/grub/x86_64-efi, so the 2.14 modules a nixpkgs bump wrote were
      # unloadable by it), then the systemd-boot the original 25.11 install
      # left behind. Policy since:
      #   * install to the removable path /EFI/BOOT/BOOTX64.EFI, which the
      #     firmware's "Internal Hard Disk" entry loads regardless of NVRAM;
      #   * never launch or chainload another GRUB core from this ESP: every
      #     core on it shares one module directory, and any core not written
      #     by the same grub-install run breaks on the next nixpkgs bump;
      #   * the firmware re-creates the "ubuntu" entry, first in BootOrder,
      #     whenever that file exists (deleting the entry lasted one boot), so
      #     the file is kept as a byte copy of BOOTX64.EFI, refreshed on every
      #     install (khome.espCheck.loaderMirrors below);
      #   * esp-check (non_home_manager_config/esp-check.nix) runs after every
      #     install and fails the rebuild when the ESP disagrees with the
      #     profile, the removable image is not GRUB, or any firmware entry
      #     would start a GRUB core other than it.
      # Flipping efiInstallAsRemovable does not by itself re-run grub-install
      # (its state file ignores the flag): the first rebuild after this change
      # needs `nh os boot --install-bootloader`; esp-check says so if forgotten.

      # Back to 5s: 1s was technically enough (any keypress opens the menu for
      # older generations / the Ubuntu entry) but left no room to actually
      # read the entries, and the boot-speed win never justified the misses.
      timeout = 5;
      efi = {
        # nixpkgs asserts this off when efiInstallAsRemovable is on. Nothing
        # is lost: the NVRAM entry it used to write existed but sat outside
        # BootOrder on this firmware, so NVRAM never chose the loader here.
        canTouchEfiVariables = false;
        efiSysMountPoint = "/boot";
      };
      grub = {
        enable = true;
        device = "nodev";
        efiSupport = true;
        efiInstallAsRemovable = true;
        # The installer turns this on by itself when /boot is a different
        # filesystem from the store; pinned so the ESP layout esp-check
        # verifies (/boot/kernels/<store-name>) never depends on detection.
        copyKernels = true;
        useOSProber = false;
        # Must stay <= the `--keep N` of programs.nh.clean (configuration.nix):
        # GRUB lists this many generations; GC must never delete one it lists.
        configurationLimit = 10;

        # Undertale mirror-scene theme: the boot menu renders inside the
        # "Despite everything, it's still you." dialogue box.
        theme = pkgs.callPackage ../grub_theme { };
        # After choosing an entry GRUB tears the menu down and shows its
        # terminal background while loading the kernel — by default a gray
        # NixOS-logo wallpaper. Show the theme scene with the SOUL heart in
        # the bottom-left of the dialogue box instead: together with the
        # heart cursor in the menu this reads as the soul jumping to the
        # corner when you choose an entry.
        splashImage = "${config.boot.loader.grub.theme}/background-selected.png";
        splashMode = "stretch";
        # Panel-native 16:10 mode; the theme background is authored at 1920x1200.
        gfxmodeEfi = "1920x1200,auto";

        extraEntries = ''
          # Ubuntu: run its own grub.cfg from its /boot partition
          # (/dev/nvme0n1p2, ext4) inside THIS GRUB; its initrd unlocks its
          # LUKS root (/dev/nvme0n1p3) as before. Not a chainloader to
          # /EFI/ubuntu: its shimx64.efi is this GRUB's mirror, and Ubuntu's
          # own shim (shimx64.efi.backup) has no grubx64.efi left to load.
          menuentry "Ubuntu" {
            insmod part_gpt
            insmod ext2
            search --set=root --fs-uuid 6ff714da-bb16-4d42-8581-5082d45d2176
            configfile /grub/grub.cfg
          }
        '';
      };
    };
  };

  # See the loader policy above: whatever the firmware's "ubuntu" entry loads
  # must be this install's GRUB.
  khome.espCheck.loaderMirrors = [ "EFI/ubuntu/shimx64.efi" ];

  # noatime: no metadata write per file read (store scans, builds, greps).
  # compress=zstd:1: cheap transparent compression, new writes only.
  # discard=async: batched TRIM (needs allowDiscards on the LUKS device).
  # Mount options are per-device on btrfs — keep both subvol mounts identical.
  fileSystems."/" = {
    device = "/dev/mapper/luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "noatime"
      "compress=zstd:1"
      "discard=async"
    ];
  };
  fileSystems."/home" = {
    device = "/dev/mapper/luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "noatime"
      "compress=zstd:1"
      "discard=async"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/701C-C166";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
      # Fail fast (5s) instead of systemd's long default wait if the ESP
      # doesn't show up. Deliberately NOT "nofail": nofail is what let a
      # rebuild report success against a missing /boot, leaving the
      # bootloader on a stale kernel whose modules a later GC then deleted
      # out from under it (kernel-bootloader-drift incident).
      "x-systemd.device-timeout=5s"
    ];
  };

  swapDevices = [ ];

  services = {
    xserver.videoDrivers = [
      "nvidia"
    ]; # Have nvidia and intel GPUs active
    logind.settings.Login.HandleLidSwitchDocked = "suspend"; # Suspend when laptop lid is closed but computer is docked to monitors / keyboard
    logind.settings.Login.HandleLidSwitch = "suspend"; # Specifies what to do when the laptop lid is closed.
  };

  hardware = {
    enableAllFirmware = true; # Enable firmware that is not free
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        libva-vdpau-driver
        libvdpau-va-gl
        intel-compute-runtime
        # iHD VA-API driver: video decode on the iGPU media block. The session
        # already forces LIBVA_DRIVER_NAME=iHD (hyprland/hyprland.lua), so
        # without this package VA-API fails outright and video decodes on CPU.
        intel-media-driver
      ];
      enable32Bit = true;
    };
    nvidia = {
      # 595.84 breaks the Proton/Wine Sparkle graphical client: libnvidia-ptxjitcompiler
      # raises EXCEPTION_FLT_DIVIDE_BY_ZERO on a native thread Wine can't dispatch to, so the
      # game dies ~1s in with exit code 0. Verified by running the same game build that worked
      # on 580 (2026-06-30) against 595 — identical crash. Keep 580 until 595+ is retested.
      package = config.boot.kernelPackages.nvidiaPackages.latest;
      # package = config.boot.kernelPackages.nvidiaPackages.stable;
      # package = config.boot.kernelPackages.nvidiaPackages.legacy_580;
      modesetting.enable = true;
      powerManagement = {
        enable = true;
        finegrained = true;
      };
      open = true; # Use the open-source NVIDIA kernel modules (required on newer GPUs)
      nvidiaSettings = true;
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        # Make sure to use the correct Bus ID values for your system!
        # This can be retrieved by running: sudo pciutils -c lspci -d ::03xx
        # Follow instructions in https://wiki.nixos.org/wiki/NVIDIA
        intelBusId = lib.mkForce "PCI:00:02:0";
        nvidiaBusId = lib.mkForce "PCI:02:00:0";
      };
    };

    # Bluetooth
  };

  nix.settings = {
    substituters = [
      # Cache for CUDA things
      "https://cuda-maintainers.cachix.org"
      # nix-community hosts neovim-nightly-overlay builds (danvim wraps nvim
      # nightly) plus much of the rest of the nix-community ecosystem.
      "https://nix-community.cachix.org"
    ];
    trusted-public-keys = [
      "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
    ];
    # The default 64 MiB download buffer stalls substitution of big closures
    # (nvidia/cuda paths) with "download buffer is full" warnings.
    download-buffer-size = 268435456;
    http-connections = 50;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
