# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{

  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # For theming
  programs.dconf.enable = true;

  boot.loader = {
    initrd = {
      kernelModules = [ ];
      availableKernelModules = [
        "xhci_pci"
        "thunderbolt"
        "nvme"
        "usb_storage"
        "usbhid"
        "sd_mod"
      ];
      luks.devices."luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74".device =
        "/dev/disk/by-uuid/cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    };
    kernelModules = [ "kvm-intel" ];
    extraModulePackages = [ ];

    loader.systemd-boot.configurationLimit = 10; # Empirically tested so that we don't run out of space in '/boot'
    efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot";
    };
    grub = {
      enable = true;
      device = "nodev";
      efiSupport = true;
      useOSProber = false;
      configurationLimit = 10;

      extraEntries = ''
        # Chainload to Ubuntu's GRUB config file
        menuentry "Ubuntu" {
          insmod part_gpt
          insmod fat
          insmod search_fs_uuid
          search --set=root --fs-uuid 701C-C166
          chainloader /EFI/ubuntu/grubx64.efi.backup
        }

      '';
    };
  };

  fileSystems."/" = {
    device = "/dev/mapper/luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };
  fileSystems."/home" = {
    device = "/dev/mapper/luks-cf747f68-c4d1-4a72-8589-e8ca20b09a74";
    fsType = "btrfs";
    options = [ "subvol=@home" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/701C-C166";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [ ];

  services = {
    xserver.videoDrivers = [
      "nvidia"
      "amdgpu"
    ]; # Have nvidia and amd GPUs active
    logind.lidSwitchDocked = "suspend"; # Suspend when laptop lid is closed but computer is docked to monitors / keyboard
    logind.lidSwitch = "suspend"; # Specifies what to do when the laptop lid is closed.
  };

  hardware = {
    enableAllFirmware = true; # Enable firmware that is not free
    graphics = {
      enable = true;
      extraPackages = with pkgs; [
        libva-vdpau-driver
        # vaapiVdpau  old version, stuck cuz of manager rev=2d55a52963d8a3856792e2fd6604f307176026bc
        libvdpau-va-gl
        intel-compute-runtime
      ];
      enable32Bit = true;
    };
    nvidia = {
      modesetting.enable = true;
      powerManagement = {
        enable = true;
        finegrained = true;
      };
      open = false; # Don't use open source drivers (use closed-source)
      nvidiaSettings = true;
      prime = {
        offload = {
          enable = true;
          enableOffloadCmd = true;
        };
        # Make sure to use the correct Bus ID values for your system!
        # This can be retrieved by running: sudo lshw -c display
        # amdgpuBusId = "PCI:06:00:0";
        # nvidiaBusId = "PCI:01:00:0";
      };
    };

    # Bluetooth
    bluetooth = {
      enable = true;
    };
  };

  # Cache for CUDA things
  nix.settings = {
    substituters = [
      "https://cuda-maintainers.cachix.org"
    ];
    trusted-public-keys = [
      "cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E="
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
