{pkgs, lib, ...}:
{
  # systemPackages, not defaultPackages: the latter is the NixOS default set
  # (perl/rsync/strace) and assigning to it removes those from the system.
  environment.systemPackages = with pkgs; [
    impala # iwd TUI. needs conman
    iwgtk # iwd GUI
  ];
  networking.hostName = "fell-omen"; # Define your hostname.

  # NOTE(dani): If things fail, enable this and disable below
  # networking.networkmanager.enable = true; # Easiest to use and most distros use this by default.

  # Gotcha: connman soft-blocks (rfkill) any technology whose saved Enable=
  # flag in /var/lib/connman/settings is off, on every boot. A manual
  # `rfkill unblock` powers it back but is NOT persisted — if radios come up
  # blocked again, fix it once with `connmanctl disable/enable <tech>`.
  services.connman.enable = true;
  services.connman.wifi.backend = "iwd";
  networking.wireless.iwd.enable = true;

  # Disable connman's built-in DNS proxy (2026-08-12). By default connman runs a
  # caching resolver on 127.0.0.1:53 + [::1]:53 and writes *those* into
  # resolv.conf instead of the real nameservers. Two problems:
  #
  #   1. It's buggy. 251 dropped replies in the 7 days before this was written
  #      ("Failed to send response N: Bad file descriptor", "Cannot send cached
  #      DNS response"), on every single day. Each drop is a query the client
  #      has to time out and retry.
  #   2. It's a redundant hop. tailscaled owns /etc/resolv.conf and points
  #      everything at 100.100.100.100; its upstream was connman's proxy, which
  #      then forwarded to the router. Three hops for every non-tailnet lookup.
  #
  # With --nodnsproxy connman writes the router's real nameservers, so tailscale
  # forwards straight to them. Drop this flag to get the proxy (and its cache)
  # back. Note this only works out because tailscale learns its upstream by
  # reading whatever connman put in /etc/resolv.conf — see the resolv.conf note
  # below before touching either side.
  services.connman.extraFlags = [ "--nodnsproxy" ];

  # Do NOT "fix" the boot message
  #   connmand: Cannot create /var/run/connman/resolv.conf falling back to /etc/resolv.conf
  # by giving the unit a RuntimeDirectory. The fallback is load-bearing: writing
  # /etc/resolv.conf directly is exactly how tailscaled (direct mode) discovers
  # an upstream resolver before it takes the file over and backs the old one up
  # to /etc/resolv.pre-tailscale-backup.conf. Divert connman's write to
  # /run/connman and tailscale is left with no upstream at all.

  # tailscaled was silently failing to manage DNS at all (2026-08-28). NixOS's
  # tailscale module puts openresolv on tailscaled's PATH whenever
  # networking.resolvconf.enable is true (the default), which makes tailscaled
  # prefer resolvconf-mode DNS instead of the "direct" mode the comment above
  # assumes. openresolv refuses to touch /etc/resolv.conf unless its first
  # line is its own "# Generated by resolvconf" signature — connman's raw
  # write above never carries that, so every `resolvconf -a ...` call
  # (tailscaled's DNS push, and NixOS's own network-local-commands.service
  # registering an empty static record) failed with "signature mismatch" on
  # every boot and every reconnect. Disabling resolvconf drops openresolv
  # from tailscaled's PATH, so it falls back to direct mode and actually
  # manages /etc/resolv.conf as the comment above intends.
  networking.resolvconf.enable = false;

  # Enable the OpenSSH daemon.
  services.openssh.enable = true;

  # mDNS / `.local` resolution. Silences the boot warning
  # "No NSS support for mDNS detected, consider installing nss-mdns!".
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };

  # No `networking.useDHCP` here on purpose. connman does its own DHCP per
  # service, so the connman module force-sets useDHCP = false and *asserts* that
  # it isn't true. A `networking.useDHCP = lib.mkDefault true;` line survives the
  # build (the module's plain `false` outranks mkDefault) but is dead config that
  # would break evaluation the moment the mkDefault were dropped.

  # Open ports in the firewall.
  networking.firewall.allowedUDPPorts = [ 53317 ];  # for localsend discovery (multicast)
  networking.firewall.allowedTCPPorts = [ 53317 ];  # for localsend transfer (HTTPS upload)

  # Or disable the firewall altogether.
  # networking.firewall.enable = false;
}
